application: hashbounty
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- remote_api: on
- datastore_admin: on

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats/

handlers:
- url: /admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin/__init__.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /.*
  script: main.py
